#!/usr/bin/env bash

# Note: use lowercase names for the Docker images
DOCKER_IMAGE="bnorman3/med-device-connect-ui"
# "testing" is the latest dev build, usually matching the code in the "master" branch
DOCKER_TAG="$DOCKER_IMAGE:testing"

docker push $DOCKER_TAG
